apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-tls
  namespace: mgmt
spec:
  secretName: registry-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days before expiry
  subject:
    organizations:
      - dev-cluster
  commonName: registry.mgmt.svc.cluster.local
  dnsNames:
    - registry
    - registry.mgmt
    - registry.mgmt.svc
    - registry.mgmt.svc.cluster.local
    - registry.localhost
  ipAddresses:
    - 127.0.0.1
  usages:
    - server auth
    - client auth  # For mTLS
  issuerRef:
    name: registry-ca-issuer
    kind: ClusterIssuer
