apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-grpcserver-tls
  namespace: app-namespace
spec:
  secretName: frontend-grpcserver-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days before expiry
  subject:
    organizations:
      - dev-cluster
  commonName: frontend
  usages:
    - client auth
  issuerRef:
    name: grpcserver-ca-issuer
    kind: ClusterIssuer
