apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Official nginx ingress controller for Kind
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
