apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grpcserver-server-tls
  namespace: app-namespace
spec:
  secretName: grpcserver-server-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days before expiry
  subject:
    organizations:
      - dev-cluster
  commonName: grpcserver.app-namespace.svc.cluster.local
  dnsNames:
    - grpcserver
    - grpcserver.app-namespace
    - grpcserver.app-namespace.svc
    - grpcserver.app-namespace.svc.cluster.local
  usages:
    - server auth
  issuerRef:
    name: grpcserver-ca-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grpcserver-postgres-tls
  namespace: app-namespace
spec:
  secretName: grpcserver-postgres-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days before expiry
  subject:
    organizations:
      - dev-cluster
  commonName: grpcserver
  usages:
    - client auth
  issuerRef:
    name: postgres-ca-issuer
    kind: ClusterIssuer
