apiVersion: v1
kind: Service
metadata:
  name: "{{name}}"
  namespace: "{{namespace}}"
  labels:
    app.kubernetes.io/name: "{{name}}"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: "{{name}}"
  ports:
    - name: grpc
      port: 25000
      protocol: TCP
      targetPort: grpc-port
    - name: http
      port: 26000
      protocol: TCP
      targetPort: http-port
