apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: trust-manager
    repo: oci://quay.io/jetstack/charts
    version: v0.20.2
    releaseName: trust-manager
    namespace: cert-manager
    valuesInline:
      crds:
        enabled: true
