apiVersion: batch/v1
kind: Job
metadata:
  name: "dbmate-{{DATABASE}}"
  namespace: app-namespace
spec:
  template:
    spec:
      containers:
      - name: "dbmate-{{DATABASE}}"
        image: "registry.localhost:5001/dbmate-{{DATABASE}}:latest"
        imagePullPolicy: Always
