apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dbmate-tls
  namespace: app-namespace
spec:
  secretName: dbmate-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days before expiry
  subject:
    organizations:
      - dev-cluster
  commonName: dbmate
  usages:
    - client auth
  issuerRef:
    name: postgres-ca-issuer
    kind: ClusterIssuer
