apiVersion: v1
kind: Secret
metadata:
  name: kratos-secrets
  namespace: app-namespace
type: Opaque
stringData:
  # Generate a secure secret in production: openssl rand -base64 32
  cookie-secret: "sFyVxq+cvVYoRQy8tdVqPcAxslRD++6ZsB8xGwUO5g0="
