apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: app-namespace
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: grpcserver-transport
  namespace: app-namespace
spec:
  serverName: grpcserver.app-namespace.svc.cluster.local
  rootCAsSecrets:
    - grpcserver-traefik-ca-bundle
  certificatesSecrets:
    - traefik-grpcserver-tls

