apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grpcserver-tls
  namespace: app-namespace
spec:
  secretName: grpcserver-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days before expiry
  subject:
    organizations:
      - dev-cluster
  commonName: grpcserver.app-namespace.svc.cluster.local
  dnsNames:
    - grpcserver
    - grpcserver.app-namespace
    - grpcserver.app-namespace.svc
    - grpcserver.app-namespace.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
  usages:
    - server auth
    - client auth  # For mTLS
  issuerRef:
    name: grpcserver-ca-issuer
    kind: ClusterIssuer
