apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ingress.yaml

# Rewrite image references to use in-cluster registry
images:
  - name: "{{name}}"
    newName: "registry.localhost:5001/grpcserver"
    newTag: latest