apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

# Rewrite image references to use in-cluster registry
images:
  - name: "{{name}}"
    newName: "registry.localhost/grpcserver"
    newTag: latest