apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{name}}"
  namespace: "{{namespace}}"
  labels:
    app.kubernetes.io/name: "{{name}}"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{name}}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{name}}"
    spec:
      shareProcessNamespace: true # so we can attach a debugger
      serviceAccountName: "{{name}}"
      containers:
      - name: "{{name}}"
        image: "{{name}}"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: environment-volume
          mountPath: "/environment"
          readOnly: true
        - name: 'database-credentials'
          mountPath: '/mnt/database-credentials/application'
          readOnly: true
        - name: client-certs
          mountPath: /mnt/client-certs
          readOnly: true
        - name: postgres-ca
          mountPath: /mnt/postgres-ca
          readOnly: true
        - name: empty-dir
          mountPath: /tmp
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: 50m # Min
            memory: 256Mi
          limits:
            memory: 1Gi
      volumes:
      - name: environment-volume
        configMap:
          name: environment
      - name: database-credentials
        configMap:
          name: environment
      - name: client-certs
        secret:
          secretName: "{{name}}-tls"
      - name: postgres-ca
        configMap:
          name: postgres-ca-bundle
      - name: empty-dir
        emptyDir: {}
